plugins:
  axiom_curfew_enabled:
    default: false
    client: false

  axiom_curfew_groups:
    default: ""
    type: group_list
    client: false

  axiom_curfew_timezone:
    default: "Europe/London"
    type: string
    client: false

  axiom_curfew_monday_start:
    default: "21:00"
    type: string
    client: false

  axiom_curfew_monday_end:
    default: "07:00"
    type: string
    client: false

  axiom_curfew_tuesday_start:
    default: "21:00"
    type: string
    client: false

  axiom_curfew_tuesday_end:
    default: "07:00"
    type: string
    client: false

  axiom_curfew_wednesday_start:
    default: "21:00"
    type: string
    client: false

  axiom_curfew_wednesday_end:
    default: "07:00"
    type: string
    client: false

  axiom_curfew_thursday_start:
    default: "21:00"
    type: string
    client: false

  axiom_curfew_thursday_end:
    default: "07:00"
    type: string
    client: false

  axiom_curfew_friday_start:
    default: "21:00"
    type: string
    client: false

  axiom_curfew_friday_end:
    default: "07:00"
    type: string
    client: false

  axiom_curfew_saturday_start:
    default: "21:00"
    type: string
    client: false

  axiom_curfew_saturday_end:
    default: "07:00"
    type: string
    client: false

  axiom_curfew_sunday_start:
    default: "21:00"
    type: string
    client: false

  axiom_curfew_sunday_end:
    default: "07:00"
    type: string
    client: false

  axiom_curfew_message:
    default: "Posting is closed for pupils during curfew hours. You can still read and return later."
    type: string
    client: false
